/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface TokensSchema {
  tokens: (
    | {
        address: string
        decimals: number
        image: string
        name: string
        symbol: string
      }
    | {
        address: string
        decimals: number
        image?: string
        mintUrl?: string
        name: string
        protocol: string
        symbol: string
        type: 'amm' | 'cdp' | 'perpetuals' | 'unknown' | 'vault'
        underlyingTokens: string[]
      }
  )[]
  [k: string]: unknown
}
